apiVersion: v1
kind: ServiceMonitor
metadata:
  name: questboard-backend-monitor
  namespace: questboard
  labels:
    app: backend
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: questboard-alerts
  namespace: questboard
  labels:
    prometheus: kube-prometheus
spec:
  groups:
  - name: questboard.rules
    interval: 30s
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_request_total{job="backend",status=~"5.."}[5m])) by (job)
        /
        sum(rate(http_request_total{job="backend"}[5m])) by (job)
        > 0.05
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.job }}"
    
    - alert: HighResponseTime
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="backend"}[5m])) by (le, job))
        > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High response time detected
        description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}"
    
    - alert: PodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace="questboard"}[15m])
        > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Pod is crash looping
        description: "Pod {{ $labels.pod }} is crash looping"
    
    - alert: HighMemoryUsage
      expr: |
        container_memory_working_set_bytes{namespace="questboard"}
        / 
        container_spec_memory_limit_bytes{namespace="questboard"}
        > 0.9
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: "Memory usage is {{ $value | humanizePercentage }} for {{ $labels.pod }}"
    
    - alert: DatabaseConnectionFailure
      expr: |
        pg_up{namespace="questboard"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Database connection failure
        description: "Cannot connect to PostgreSQL database"