apiVersion: v1
kind: Secret
metadata:
  name: questboard-secrets
  namespace: questboard
type: Opaque
stringData:
  JWT_SECRET: "your-very-secure-jwt-secret-minimum-32-characters"
  REFRESH_TOKEN_SECRET: "your-very-secure-refresh-token-secret"
  SESSION_SECRET: "your-very-secure-session-secret"
  DB_USER: "questboard"
  DB_PASSWORD: "your-secure-database-password"
  REDIS_PASSWORD: "your-secure-redis-password"
  GOOGLE_CLIENT_ID: "your-google-client-id.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  ELASTICSEARCH_PASSWORD: "your-elasticsearch-password"
  EMAIL_PASSWORD: "your-email-password"
  SENTRY_DSN: "https://your-sentry-dsn@sentry.io/project-id"
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  BACKUP_ENCRYPTION_KEY: "your-backup-encryption-key"
  ADMIN_EMAILS: "admin@questboard.com,support@questboard.com"